### PR TITLE
Changed gendered terms to be gender-neutral

### PR DESCRIPTION
**Pull request by gonyere**
Changed a handful of gendered terms to be gender-neutral, and one typo of 'he' to 'the' where appropriate.

### CODE REVIEW

**Comment by blackcrack** [comment]
what should this with f.. genderism.. ! IT, should disable !  bull shit .. !

**Comment by Jehan** [comment]
@gonyere Sure, but Github is only a read-only mirror. We don't accept patches here. Please contribute to: https://gitlab.gnome.org/GNOME/gimp/ (a bot regularly passes here and would soon close this MR anyway).

@blackcrack Though sometimes people are acting over-the-line, in particular when they are being directly confrontational and mean to others, here I see nothing of the sort. It's small changes, fair ones (not assuming people are only men) and asked without any bad behavior. So why not? I see no reasons to refuse the changes. Please let's keep respectful to each others. Thanks.

**Comment by blackcrack** [comment]
respectful in all honor, but playing the game with is something other..
happy weekend to you :)

**Comment by gnomesysadmins** [comment]
Thank you for contributing to gimp!

gimp uses GitLab for code review. As such we have forwarded
your contribution to the GNOME official GitLab instance:

https://gitlab.gnome.org/GNOME/gimp/-/issues/7496

GNOME's GitLab instance also supports GitHub as one of the possible
authentication method in case you'd like to follow up on the above
issue. You can login at the following URL:

https://gitlab.gnome.org/users/sign_in

If you are interested in sticking around within the GNOME community we
encourage you to read the following documents:

https://www.gnome.org/get-involved
and
https://wiki.gnome.org/Newcomers

**Pull request closed without merging**
