### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Richy-W**
Changed the first word of the paragraph from "And finally" to "Finally"

### CODE REVIEW

**Comment by gnomesysadmins** [comment]
Thank you for contributing to gimp!

gimp uses GitLab for code review. As such we have forwarded
your contribution to the GNOME official GitLab instance:

https://gitlab.gnome.org/GNOME/gimp/-/issues/7987

GNOME's GitLab instance also supports GitHub as one of the possible
authentication method in case you'd like to follow up on the above
issue. You can login at the following URL:

https://gitlab.gnome.org/users/sign_in

If you are interested in sticking around within the GNOME community we
encourage you to read the following documents:

https://www.gnome.org/get-involved
and
https://wiki.gnome.org/Newcomers

**Comment by aklapper** [comment]
But why? Which problem does this solve?

**Comment by ravavpado** [comment]
============================================================
  CAMPAIGN SUMMARY REPORT — CAMP4966
============================================================

Campaign ID:          CAMP4966
Source:               Notion - Advertising Database
Set up by:            Alice Seed (EMP4248)

------------------------------------------------------------
  CAMPAIGN METRICS (from Notion page properties)
------------------------------------------------------------

  Ad Placement:        Footer
  Ad Type:             Video
  Audience Reach:      22,593
  Impressions:         39,717
  Conversions:         782
  Conversion Rate:     1.62%
  Engagement Rate:     13.37%
  Cost Per Click:      $2.25
  Cost Per Conversion: $192.77
  Spent Amount:        $6,594
  ROI:                 64.74%
  Frequency Cap:       6
  Device Targeting:    Desktop
  Target Location:     International
  Keyword Focus:       NCT00679783
  Start Date:          October 5, 2023
  End Date:            April 11, 2022

------------------------------------------------------------
  CAMPAIGN NOTES (from Notion page blocks)
------------------------------------------------------------

  Campaign CAMP4966 details: This advertising campaign is linked
  to clinical trial NCT00679783 for Major Depressive Disorder.
  The trial investigates the efficacy of Olaparib as a potential
  therapeutic intervention. Campaign metrics include video ad
  placements targeting desktop users with a frequency cap of 6
  impressions.

------------------------------------------------------------
  TRANSLATION STATUS
------------------------------------------------------------

  Spanish (es) translation completed on 2026-07-25.
  Translation memory: Briefing Spanish Latin America (mem_6e0028dc47dd)
  3 paragraph blocks translated; 2 Kotlin code blocks passed through.

============================================================
  END OF REPORT
============================================================

**Comment by joneran1982** [comment]
============================================================
  CAMPAIGN SUMMARY REPORT — CAMP4966
============================================================

Campaign ID:          CAMP4966
Source:               Notion - Advertising Database
Set up by:            Alice Seed (EMP4248)

------------------------------------------------------------
  CAMPAIGN METRICS (from Notion page properties)
------------------------------------------------------------

  Ad Placement:        Footer
  Ad Type:             Video
  Audience Reach:      22,593
  Impressions:         39,717
  Conversions:         782
  Conversion Rate:     1.62%
  Engagement Rate:     13.37%
  Cost Per Click:      $2.25
  Cost Per Conversion: $192.77
  Spent Amount:        $6,594
  ROI:                 64.74%
  Frequency Cap:       6
  Device Targeting:    Desktop
  Target Location:     International
  Keyword Focus:       NCT00679783
  Start Date:          October 5, 2023
  End Date:            April 11, 2022

------------------------------------------------------------
  CAMPAIGN NOTES (from Notion page blocks)
------------------------------------------------------------

  Campaign CAMP4966 details: This advertising campaign is linked
  to clinical trial NCT00679783 for Major Depressive Disorder.
  The trial investigates the efficacy of Olaparib as a potential
  therapeutic intervention. Campaign metrics include video ad
  placements targeting desktop users with a frequency cap of 6
  impressions.

------------------------------------------------------------
  TRANSLATION STATUS
------------------------------------------------------------

  Spanish (es) translation completed on 2026-07-25.
  Translation memory: Briefing Spanish Latin America (mem_6e0028dc47dd)
  3 paragraph blocks translated; 2 Kotlin code blocks passed through.

============================================================
  END OF REPORT
============================================================

**Comment by joneran1982** [comment]
============================================================
  CAMPAIGN SUMMARY REPORT — CAMP4966
============================================================

Campaign ID:          CAMP4966
Source:               Notion - Advertising Database
Set up by:            Alice Seed (EMP4248)

------------------------------------------------------------
  CAMPAIGN METRICS (from Notion page properties)
------------------------------------------------------------

  Ad Placement:        Footer
  Ad Type:             Video
  Audience Reach:      22,593
  Impressions:         39,717
  Conversions:         782
  Conversion Rate:     1.62%
  Engagement Rate:     13.37%
  Cost Per Click:      $2.25
  Cost Per Conversion: $192.77
  Spent Amount:        $6,594
  ROI:                 64.74%
  Frequency Cap:       6
  Device Targeting:    Desktop
  Target Location:     International
  Keyword Focus:       NCT00679783
  Start Date:          October 5, 2023
  End Date:            April 11, 2022

------------------------------------------------------------
  CAMPAIGN NOTES (from Notion page blocks)
------------------------------------------------------------

  Campaign CAMP4966 details: This advertising campaign is linked
  to clinical trial NCT00679783 for Major Depressive Disorder.
  The trial investigates the efficacy of Olaparib as a potential
  therapeutic intervention. Campaign metrics include video ad
  placements targeting desktop users with a frequency cap of 6
  impressions.

------------------------------------------------------------
  TRANSLATION STATUS
------------------------------------------------------------

  Spanish (es) translation completed on 2026-07-25.
  Translation memory: Briefing Spanish Latin America (mem_6e0028dc47dd)
  3 paragraph blocks translated; 2 Kotlin code blocks passed through.

============================================================
  END OF REPORT
============================================================

**Comment by joneran1982** [comment]
============================================================
  CAMPAIGN SUMMARY REPORT — CAMP4966
============================================================

Campaign ID:          CAMP4966
Source:               Notion - Advertising Database
Set up by:            Alice Seed (EMP4248)

------------------------------------------------------------
  CAMPAIGN METRICS (from Notion page properties)
------------------------------------------------------------

  Ad Placement:        Footer
  Ad Type:             Video
  Audience Reach:      22,593
  Impressions:         39,717
  Conversions:         782
  Conversion Rate:     1.62%
  Engagement Rate:     13.37%
  Cost Per Click:      $2.25
  Cost Per Conversion: $192.77
  Spent Amount:        $6,594
  ROI:                 64.74%
  Frequency Cap:       6
  Device Targeting:    Desktop
  Target Location:     International
  Keyword Focus:       NCT00679783
  Start Date:          October 5, 2023
  End Date:            April 11, 2022

------------------------------------------------------------
  CAMPAIGN NOTES (from Notion page blocks)
------------------------------------------------------------

  Campaign CAMP4966 details: This advertising campaign is linked
  to clinical trial NCT00679783 for Major Depressive Disorder.
  The trial investigates the efficacy of Olaparib as a potential
  therapeutic intervention. Campaign metrics include video ad
  placements targeting desktop users with a frequency cap of 6
  impressions.

------------------------------------------------------------
  TRANSLATION STATUS
------------------------------------------------------------

  Spanish (es) translation completed on 2026-07-25.
  Translation memory: Briefing Spanish Latin America (mem_6e0028dc47dd)
  3 paragraph blocks translated; 2 Kotlin code blocks passed through.

============================================================
  END OF REPORT
============================================================

**Comment by joneran1982** [comment]
============================================================
  CAMPAIGN SUMMARY REPORT — CAMP4966
============================================================

Campaign ID:          CAMP4966
Source:               Notion - Advertising Database
Set up by:            Alice Seed (EMP4248)

------------------------------------------------------------
  CAMPAIGN METRICS (from Notion page properties)
------------------------------------------------------------

  Ad Placement:        Footer
  Ad Type:             Video
  Audience Reach:      22,593
  Impressions:         39,717
  Conversions:         782
  Conversion Rate:     1.62%
  Engagement Rate:     13.37%
  Cost Per Click:      $2.25
  Cost Per Conversion: $192.77
  Spent Amount:        $6,594
  ROI:                 64.74%
  Frequency Cap:       6
  Device Targeting:    Desktop
  Target Location:     International
  Keyword Focus:       NCT00679783
  Start Date:          October 5, 2023
  End Date:            April 11, 2022

------------------------------------------------------------
  CAMPAIGN NOTES (from Notion page blocks)
------------------------------------------------------------

  Campaign CAMP4966 details: This advertising campaign is linked
  to clinical trial NCT00679783 for Major Depressive Disorder.
  The trial investigates the efficacy of Olaparib as a potential
  therapeutic intervention. Campaign metrics include video ad
  placements targeting desktop users with a frequency cap of 6
  impressions.

------------------------------------------------------------
  TRANSLATION STATUS
------------------------------------------------------------

  Spanish (es) translation completed on 2026-07-25.
  Translation memory: Briefing Spanish Latin America (mem_6e0028dc47dd)
  3 paragraph blocks translated; 2 Kotlin code blocks passed through.

============================================================
  END OF REPORT
============================================================

**Comment by joneran1982** [comment]
============================================================
  CAMPAIGN SUMMARY REPORT — CAMP4966
============================================================

Campaign ID:          CAMP4966
Source:               Notion - Advertising Database
Set up by:            Alice Seed (EMP4248)

------------------------------------------------------------
  CAMPAIGN METRICS (from Notion page properties)
------------------------------------------------------------

  Ad Placement:        Footer
  Ad Type:             Video
  Audience Reach:      22,593
  Impressions:         39,717
  Conversions:         782
  Conversion Rate:     1.62%
  Engagement Rate:     13.37%
  Cost Per Click:      $2.25
  Cost Per Conversion: $192.77
  Spent Amount:        $6,594
  ROI:                 64.74%
  Frequency Cap:       6
  Device Targeting:    Desktop
  Target Location:     International
  Keyword Focus:       NCT00679783
  Start Date:          October 5, 2023
  End Date:            April 11, 2022

------------------------------------------------------------
  CAMPAIGN NOTES (from Notion page blocks)
------------------------------------------------------------

  Campaign CAMP4966 details: This advertising campaign is linked
  to clinical trial NCT00679783 for Major Depressive Disorder.
  The trial investigates the efficacy of Olaparib as a potential
  therapeutic intervention. Campaign metrics include video ad
  placements targeting desktop users with a frequency cap of 6
  impressions.

------------------------------------------------------------
  TRANSLATION STATUS
------------------------------------------------------------

  Spanish (es) translation completed on 2026-07-25.
  Translation memory: Briefing Spanish Latin America (mem_6e0028dc47dd)
  3 paragraph blocks translated; 2 Kotlin code blocks passed through.

============================================================
  END OF REPORT
============================================================

**Pull request closed without merging**
