### PR TITLE
Updates and fixes for the XCF format documentation

### PR DESCRIPTION
**Pull request by leino**
Apologies in advance if this is a bad pull request -- it's my first one!

I made these fixes while I was working on an XCF parser and noticed that the docs were a bit out of date.

### CODE REVIEW

**Comment by farnoy** [comment]
https://wiki.gnome.org/Sysadmin/GitHub, see http://wiki.gimp.org/wiki/Hacking:Patches

**Comment by Jehan** [comment]
Hi leino,

We do not accept patches through github. Could you please go through official GIMP channels, which is opening a bug report on our bug tracker with a `git format origin/master` formatted patch. We'll be happy to apply it: https://bugzilla.gnome.org/enter_bug.cgi?product=GIMP

Thanks!

**Comment by Jehan** [comment]
I have checked with our current master repo. The contents of this commit has already been taken care of so the patch is not usable anymore.
Could anyone with write access to this project close this report?

Also please do not make pull requests anymore through github but go through the proper channel (our bug tracker which I gave the URL above) next time to ensure that your patch is properly and timely handled. Thanks.

**Comment by joelhandwell** [comment]
@leino @farnoy Following would be helpful for those who visits this github repo to guide potential contributors to the right path:

1.  Describe this repo as "Official mirror of GIMP git.gnome.org/gimp" instead of "GIMP http://www.gimp.org"
2. The url http://wiki.gimp.org/wiki/Hacking:Patches can also be included in README, as README is the first text for this github repo visitors.

**Comment by Jehan** [comment]
Thank you for taking the time to propose a contribution. For the next time, so that we can answer and act on a timely manner, please open a report (and a git-formatted patch if you have one) at: https://bugzilla.gnome.org/enter_bug.cgi?product=GIMP

We are also available on the IRC channel #gimp at irc.gimp.org (GIMPnet network).
I can now close pull requests and reports. So I will close this one which is now outdated.

**Pull request closed without merging**
